import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the shadcn CLI and overwritten on update — not ours to lint.
    "src/components/ui/**",
    "src/hooks/use-mobile.ts",
    // Hand-authored decks. `deck.js` is copied unchanged from `slides/template`
    // per its design notes, so linting it only produces warnings we must not act
    // on — a fix here would be lost on the next copy.
    "slides/**",
  ]),
]);

export default eslintConfig;
